export const ThemeLight = {
  name: "light",
  colors: {
    primary: "#ededed",
    text: "#432a78",
    textHover: "#6a00ff",
    btnHeaderSignIn: "#432a78",
    btnHeaderSignInHover: "#aaaaaa",
    btnHeaderBorder: "#cacaca",
    borderHeader: "#e0e0e0",
    backgroundBanner: "#f7f7f7",
    textBanner: "#432a78",
    footerWavesSignInAndSignUp: "#eaeaea",
  },
  BoxLoginAndRegister: {
    bg1: "#f0f0f0",
    bg2: "#cacaca",
    boxShadow1: "#777777",
    boxShadow2: "#adadad",
    text: "#432a78",
    btnBG: "#F3F6E6",
    inputBG: "#fff",
  },

  dashboard: {
    colors: {
      sideBarbackground: "#F8F8FA",
      background: "#fff",
      navItems: "#fff",
      textNavItems: "#545454",
      boxShadow1: "#d5d5d5",
      boxShadow2: "#ebebeb",
      inputSearchBG: "#eaeaea",
      inputSearchText: "#545454",
      NotificationMenuBG: "#F8F8FA",
      NotificationMenuText: "#545454",
      InfoUserText: "#545454",
      TableText: "#545454",
      TableHeaderBG: "#eaeaea",

      BoxNewsBG: "#ffffff",
      BoxNewsText: "#545454",
      NewsBG: "#eaeaea",
      NewsDescription: "#383838",
      NewsTitle: "#727272",
      NewsBoxShadow1: "#d4d4d4",
      NewsBoxShadow2: "#ffffff",
    },
  },
};

export const ThemeDark = {
  name: "dark",
  colors: {
    primary: "#553d89",
    text: "#f8f8f8",
    textHover: "#383838",
    btnHeaderSignIn: "#1b0844",
    btnHeaderSignInHover: "#1b0844",
    btnHeaderBorder: "#000",
    borderHeader: "#462f7c",
    backgroundBanner: "#222",
    textBanner: "#cacaca",
    footerWavesSignInAndSignUp: "#333",
  },
  BoxLoginAndRegister: {
    bg1: "#222",
    bg2: "#333",
    boxShadow1: "#181818",
    boxShadow2: "#212121",
    text: "#cacaca",
    btnBG: "#6a00ff",
    inputBG: "#cacaca",
  },

  dashboard: {
    colors: {
      sideBarbackground: "#2c2c2c",
      background: "#222",
      navItems: "#222",
      textNavItems: "#cacaca",
      boxShadow1: "#202020",
      boxShadow2: "#242424",
      inputSearchBG: "#2c2c2c",
      inputSearchText: "#cacaca",
      NotificationMenuBG: "#2c2c2c",
      NotificationMenuText: "#cacaca",
      InfoUserText: "#cacaca",
      TableText: "#cacaca",
      TableHeaderBG: "#2c2c2c",

      BoxNewsBG: "#222",
      BoxNewsText: "#cacaca",
      NewsBG: "#333",
      NewsDescription: "#aaaaaa",
      NewsTitle: "#c4c4c4",
      NewsBoxShadow1: "#1c1c1c",
      NewsBoxShadow2: "#282828",
    },
  },
};
